/*Create User Table */

CREATE TABLE User (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(45),
    LAST_NAME VARCHAR(45),
    MOBILE_NO BIGINT,
    EMAIL VARCHAR(45),
    PASSWORD VARCHAR(45),
    ROLE_ID INT,
    REGISTERED_AT TIMESTAMP,
    LAST_LOGIN TIMESTAMP,
    HAS_PERMISSION TINYINT NOT NULL,
    ROLES_ROLE_ID INT,
    REVIEW_ID INT,
    IMAGE BLOB,
    PRIMARY KEY (USER_ID)
);


/* Create Tutor Table */

CREATE TABLE Tutor (
TUTOR_ID INT NOT NULL AUTO_INCREMENT,
USER_ID INT NOT NULL,
IS_ACTIVE TINYINT NOT NULL,
SUBJECT_ID INT,
PRICE INT,
CV BLOB,
PRIMARY KEY (TUTOR_ID)
);


/* Create Subject Table */

CREATE TABLE SUBJECT (
SUBJECT_ID INT NOT NULL,
SUBJECT_NAME VARCHAR(45),
PRIMARY KEY (SUBJECT_ID)
);


/* Insert Into User Table */

INSERT INTO User ( FIRST_NAME,LAST_NAME, MOBILE_NO, EMAIL, PASSWORD, ROLE_ID, HAS_PERMISSION,ROLES_ROLE_ID,REVIEW_ID)
VALUES ( , , , , , , , , );


/* Insert Into Tutor Table */

INSERT INTO Tutor (USER_ID, IS_ACTIVE, SUBJECT_ID, PRICE)
VALUES ( , , , );


/* Insert Into Subject Table */

INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES ( , );


/* Delete From User Table */
DELETE FROM User WHERE USER_ID = 1;


/* Delete From Tutor Table */
DELETE FROM Tutor WHERE TUTOR_ID = 1;


/* Delete From Subject Table */
DELETE FROM Subject WHERE SUBJECT_ID = 101;
